### ISSUE TITLE
Can this card work with 'input_select' helpers?

### ISSUE THREAD

**Issue by zala143** [bernikr/lovelace-notify-card#12]
This is a great frontend card, thanks for creating it.  This card would be amazing if you could specify a list of targets via yaml list or input_select. 

Then from the frontend card, have a dropdown menu that allows you to select the target notify source you want to send to. Added bonus, if you could also write a custom message or also select from a pre defined message again from an input_select helper.

Thanks in advance,

**Comment by KevSex** [comment]
I achieved this using an input_select and using conditional cards to show depending on the input_select value.

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_select.tts_source
  - type: horizontal-stack
    cards:
      - type: conditional
        conditions:
          - entity: input_select.tts_source
            state: Phone
        card:
          type: custom:notify-card
          target: pushover
          label: Notify phone
          card_title: Send Notification
      - type: conditional
        conditions:
          - entity: input_select.tts_source
            state: Amazon Echo
        card:
          type: custom:notify-card
          target: alexa_media_kevin_s_echo
          data:
            type: tts
          label: Notify Amazon Echo
          card_title: Send Notification
      - type: conditional
        conditions:
          - entity: input_select.tts_source
            state: LG TV
        card:
          type: custom:notify-card
          target: lg_webos_smart_tv
          label: Notify TV
          card_title: Send Notification
```
<img width="487" alt="Screenshot 2022-09-07 at 19 43 27" src="https://user-images.githubusercontent.com/13280296/188954204-2dc66605-e730-469c-96de-326d96ec2762.png">
