### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by JaroslawPrzybyl** [bernikr/lovelace-notify-card#16]
Could you add possibility to set a language in this card? I tried as below, but it seems, this field is ignored:

        - type: custom:notify-card
          card_title: Send notify to Salon
          target: tts.google_say
          entity: media_player.salon
          data:
            language: pl
`

**Comment by dmaciaszek** [comment]
PR for this function https://github.com/bernikr/lovelace-notify-card/pull/17

**Comment by smenzer** [comment]
i would also like to see support to pass in the `language` data parameter.

**Comment by bernikr** [comment]
I've updated the card to be able to work with any action/service and any data now.

Please update the card and try the following config:
```yaml
type: custom:notify-card
card_title: Send notify to Salon
action: tts.google_say
data:
  entity_id: media_player.salon
  language: pl
  message: $MSG
```
