### ISSUE TITLE
Failed to call service tts/speak. required key not provided @ data['media_player_entity_id']

### ISSUE THREAD

**Issue by AlexTryHarder** [bernikr/lovelace-notify-card#23]
**Card**
`type: custom:notify-card
target: tts.speak
entity: media_player.alarm_speakers
data: **<-- tried adding this with no luck..**
  media_player_entity_id: media_player.alarm_speakers
`
**Service**
`service: tts.speak
data:
  cache: true
  message: test
  media_player_entity_id: media_player.alarm_speakers
target:
  entity_id: tts.google_en_com
`

**Comment by jccarey5** [comment]
I have the same issue

**Comment by fungio** [comment]
I made a PR https://github.com/bernikr/lovelace-notify-card/pull/28 to fix that.

**Comment by bernikr** [comment]
I've updated the card to be able to work with any action/service and any data now.

Please update the card and try the following config:
```yaml
type: custom:notify-card
action: tts.speak
data:
  cache: true
  message: $MSG
  media_player_entity_id: media_player.alarm_speakers
  target:
    entity_id: tts.google_en_com
```
