### ISSUE TITLE
TTS to Android Companion App

### ISSUE THREAD

**Issue by splasheye** [bernikr/lovelace-notify-card#29]
Not sure if this is an issue or just a my issue.
I am trying to be able to use your card to send a TTS message to my Android Cell.
If I use the service option tab in Home Assistant, the following works perfect

service: notify.mobile_app_sm_g975u1
data:
  message: TTS
  data:
    tts_text: hello

I have tried plenty option with your notify card but have had no luck.
Is it possible, and if so any help would be great.

I am trying to have a card on my dashboard that I can just type different messages and have them read out load on my phone, 
like the above option works. Thanks

**Comment by bernikr** [comment]
I've updated the card to be able to work with any action/service and any data now.

Please update the card and try the following config:
```yaml
action: notify.mobile_app_sm_g975u1
data:
  message: TTS
  data:
    tts_text: $MSG
```

**Comment by DeFlanko** [comment]
For any future searchers like i was... 

This worked for me as well: 
```yaml
type: custom:notify-card
label: Voice message
card_title: Whole Home Notification
action: notify.all_devices
data:
  message: TTS
  data:
    tts_text: "{{ msg }}"
```

where `notify.all_devices` is `notify.yaml`
```yaml
################################################################################
#                                NOTIFICATIONS
################################################################################
#notify:
- platform: group
  name: all_devices
  unique_id: all_devices
  services:
    - service: mobile_app_des_galaxy_watch7_gs5d
    - service: mobile_app_galaxy_watch7_jckk
    - service: mobile_app_sm_s938u
    - service: mobile_app_sm_s918u
    - service: my_ecobee
    - service: mobile_app_elly_sm_n975u
 ```

and `configuration.yaml` is like:
```yaml
notify: !include notify.yaml
```
