### ISSUE TITLE
Was working with Google Home Hub - stopped about a month ago 

### ISSUE THREAD

**Issue by Steeveeveeve** [bernikr/lovelace-notify-card#31]
Hi! 

Love this Notify Card - it really helps when communicating with the different rooms / kids.

Unfortunately it stopped working about a month ago.

`type: custom:notify-card
target: tts.google_translate_say
entity: media_player.kitchen_home_hub
label: Type your message here
card_title: Kitchen
notification_title: New Notification
`

The error shown is: 'Failed to perform the action tts/google_translate_say. extra keys not allowed @ data['media_player_entity_id']'

Thank you for any help!

**Comment by pink88** [comment]
Same for me. I've tried other suggestions on github and nothing works, even when editing the notify-card.js file directly to remove mention of media_player_entity_id. I am trying to use tts.google_cloud and not tts.speak or tts.google_translate_say however
https://www.home-assistant.io/integrations/google_cloud/

**Comment by bernikr** [comment]
I've updated the card to be able to work with any action/service and any data now.

Please update the card and try the following config:
```yaml
type: custom:notify-card
label: Type your message here
card_title: Kitchen
action: tts.google_translate_say
data:
  entity_id: media_player.kitchen_home_hub
  message: $MSG
```
