### ISSUE TITLE
Card not functional w/ companion app on mobile device

### ISSUE THREAD

**Issue by Zwo12** [bernikr/lovelace-notify-card#32]
Hi there, 

I don't know exactly when but eventually the notifcation card stopped working for me in terms of playing TTS on my media players. Currently I am using the latest version of HA (_2024.9.1_), HACS (_2.0.1_) and this lovelace card. 

So I started tweaking around and finally got it working in the browser (Firefox), sending TTS messages either via the button or hitting <enter>. Nevertheless using the companion app (2024.8.1, 2024.791) on my iPhone I keep getting the error message "_The action tts/google_translate_say could not be executed. Required key not provided @ data['entity_id']_" whenever I try to send a message. 

Any idea?

The YAML code looks as follows:
```yaml
type: custom:notify-card
label: Nachricht Sonos Bad
card_title: ''
action: tts.google_translate_say
data:
  message: $MSG
  title: $TITLE
  entity_id: media_player.sonos_bad
target: tts.google_translate_say
``` 

I am thankful for any hint...

**Comment by ZTHawk** [comment]
Your code is working for me.
aybe your companion app needs to refresh the UI?
After app asked to refresh, everything was working fine.

**Comment by Zwo12** [comment]
Thanks for checking, @ZTHawk!

After one of the recent updates (companion app to 2024.9.4 (2024.905) and/or HA to 2024.10.1) it is working now.
I had to get rid of the title entry under the data field though:
```yaml
type: custom:notify-card
label: Nachricht Sonos Bad
card_title: ''
action: tts.google_translate_say
data:
  message: $MSG
  entity_id: media_player.sonos_bad
target: tts.google_translate_say
```
