### ISSUE TITLE
Add "entity_id" to example

### ISSUE THREAD

**Issue by ZTHawk** [bernikr/lovelace-notify-card#33]
Could you please add the "entity_id" option to the config example? I had to find out about it inside a bug report.
Or add an additional section. In my case the action is a general one and not related to a specific device.

```
type: 'custom:notify-card'
label: Notify TV
card_title: Send Notification
notification_title:
  input: Title
action: tts.google_say
target: tts.google_say
data:
  message: $MSG
  title: $TITLE
  entity_id: media_player.nestmini_living_room
```
