### ISSUE TITLE
How to remove the input box

### ISSUE THREAD

**Issue by DeFlanko** [bernikr/lovelace-notify-card#38]
Im looking to make some **static** notifications -- in this case send a TTS to all devices in the group that "Dinner is ready!"  -- so i just need the Send icon not the input box.

looking to eventually replace all my Alexa devices with HA devices if we can get this working!

![Image](https://github.com/user-attachments/assets/42dc7c2b-4506-460f-b62f-652a4757cc25)

```yaml
type: custom:notify-card
label: Press for Dinner is Ready!
card_title: Dinner is ready!
action: notify.all_devices
data:
  message: TTS
  data:
    tts_text: Dinner is Ready!
```
