### ISSUE TITLE
`data` parameter is not at the right level

### ISSUE THREAD

**Issue by Aohzan** [bernikr/lovelace-notify-card#5]
Hello,

When I add data parameters for the service like this :
```yaml
type: custom:notify-card
...
data:
  volume_level: 0.3
  title: Announce
```
it will send to a sub data key to the service.

You have to merge the `msg` with the `data` to provide only one `data` dict:
```javascript
var service_data = Object.assign({}, this.config.data, { message: msg });
this.hass.callService(domain, target, service_data);
```

**Comment by bernikr** [comment]
As specified in the [service documentation](https://www.home-assistant.io/integrations/notify/) additional data for notification services is sent in dict named data inside of the main data dict.

You can check this [integration example](https://www.home-assistant.io/integrations/webostv/#notifications) on how the payload should usually look.

Example:

```
automation:
  - alias: "Front door motion"
    trigger:
      platform: state
      entity_id: binary_sensor.front_door_motion
      to: "on"
    action:
      service: notify.livingroom_tv
      data:
        message: "Movement detected: Front Door"
        data:
          icon: "/home/homeassistant/images/doorbell.png"
```
