### ISSUE TITLE
Needs Support for Specifying Title for Notification

### ISSUE THREAD

**Issue by fortepc** [bernikr/lovelace-notify-card#6]
Some notifications require a title to be specified, like the IOTLink notifications for example,

This is a working service call from my `developer-tools/service` page.
```yaml
service: script.notify_freddys_desktop
data:
  message: The Body of this Notification is a test too.
  title: Test Notification
```
This is what is required to send a notification, In order for it to work I must specify a title and a message.

But when trying to use this card and specifying a title like this

```yaml
type: custom:notify-card
target: script.notify_freddys_desktop_quick
data:
  title: Quick Notification
```
It doesn't work, I'm assuming this is because the service call the card is trying to do is this
```yaml
service: script.notify_freddys_desktop
data:
  message: Body of the Notification
  data:
    title: Quick Notification
```
which isn't actually specifying a title at all.

I've worked around this issue, by making a modified version of my script that specifies a title in the script, but this means I have to create a new script just for this card to use for every machine and each specific card in my UI that I may want to specify a different title for. Not ideal, but it works.

I think adding support for notify services that may require title would be worth it. My suggestion for supporting titles specifically would be to add a new option in the card's config
```yaml
specify_title: true #Enables a second text field in the card for specifying the notification title at will, defaults to false
default_title: "Quick Notification" #If specify_title is false, use this title for all notifs sent with this card, if specify_title is true, then just have this be the default contents of the title field, if not specified behavior would just be identical to how the card works now.
```
Even in applications where the title isn't required, I think everyone using this card would benefit from being able to add a title to their Notifications
