### ISSUE TITLE
How to make it work with Google Home ?

### ISSUE THREAD

**Issue by silversmarty** [bernikr/lovelace-notify-card#8]
Hello,

first of all, many thanks for this amazing card: it's exactly what I was lookin for!

I'm trying to make it work with Google Home, which have the following syntax:

```
service: tts.google_translate_say
data:
  entity_id: media_player.cuisine
  message: test
  language: fr
```
However, I've read your discussion about [Alexa](https://github.com/bernikr/lovelace-notify-card/issues/1) and it seems that the Google syntax is not compatible with what you've done for Alexa (mainly because additionnal attributes as "entity_id" (which is the target id of the desired Google Home) needs to be added in the "data" attribute.

As a reminder, the Alexa syntax seems to be:
```
service: notify.alexa_media_bad
data:
  message: MESSAGE TEXT
  data:
    type: announce
```

My question is pretty simple : How to make it work with Google Home ?

Thanks again!
